/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
void softwareDelay(uint32_t timeInMillis);

/**** Address of the Clock control register (AHB1ENR) ****/
#define	AHB1ENR 0x40023830 // base address of RCC (register control clock) register (0x40023800) + offset of AHB1ENR reg (0x30) Address of the clock control register in which GIOD D enable bit is in it

/**** Address of the GPID mode register (used to control mode) ****/
#define GPIOD_MODE 0x40020C00 // base address of GPIO D registers (0x40020C00) + offset of mode register (0x00) -> make the mode of pin 12 (bit 24 to 1 & 25 to 0) so that we can use them as general purpose output

/**** Address of the GPIOD output data register (used to write) ****/
#define GPIOD_OUTPUT 0x40020C14 // base address of GPIO D registers (0x40020C00) + offset of output register (0x14) -> make the mode of pin 12 (bit 24 to 1 & 25 to 0) so that we can use them as general purpose output

/**** Address of the GPIOD input data register (used to read) ****/
#define GPIOD_INPUT 0x40020C10 // base address of GPIO D registers (0x40020C00) + offset of input register (0x10) -> read the value of bit 0

/**** Address of the GPIOD input type register (used to either pull up / pull down / neither) ****/
#define GPIOD_PULLUP_PULLDOWN 0x40020C0C // base address of GPIO D registers (0x40020C00) + offset of input register (0x0C) -> read the value of bit 0


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
uint8_t characters[4][4] = {{'1','2','3','A'},{'4','5','6','B'},{'7','8','9','C'},{'*','0','#','D'}};

// connections
/*	stm32f407	|	keypad
 * 	PD0			|	row0
 * 	PD1			|	row1
 * 	PD2			|	row2
 * 	PD3			|	row3
 * 	PD8			|	column0
 * 	PD9			|	column1
 * 	PD10		|	column2
 * 	PD11		|	column3
 */
int main(void)
{
	uint32_t volatile *const pCtrlReg = (uint32_t*)AHB1ENR;
	uint32_t volatile *const pGPIOD_ModeReg = (uint32_t*)GPIOD_MODE;
	uint32_t volatile *const pGPIOD_OutputReg = (uint32_t*)GPIOD_OUTPUT;
	uint32_t volatile *const pGPIOD_InputReg = (uint32_t*)GPIOD_INPUT;
	uint32_t volatile *const pGPIOD_InputypeReg = (uint32_t*)GPIOD_PULLUP_PULLDOWN;
	uint8_t volatile val = 1;
	// enable the register D clock
	*pCtrlReg |= 1<<3;

	// configure PD8,PD9,PD10,PD11 as input pull up
	*pGPIOD_ModeReg &= ~(0xFF << 16); // make it as input
	*pGPIOD_InputypeReg &= ~(0xFF << 16); // make it as pull up
	*pGPIOD_InputypeReg |= (0x55 << 16);

	// configure PD0,PD1,PD2,PD3 as output
	*pGPIOD_ModeReg &= ~(0xFF); // make it as output
	*pGPIOD_ModeReg |= 0x55;

	while(1){
		// make all rows HIGH
		*pGPIOD_OutputReg |= 0x0F;

		// make every row low and check for the column
		for(int i = 0; i < 4;i++){
			*pGPIOD_OutputReg &= ~(1<<i);	// make row low at a time
			for(int j = 8; j < 12;j++){
				val = (*pGPIOD_InputReg >> j) & 1;
				if(val == 0){
					softwareDelay(200);
					printf("Key pressed which is %c\n",characters[i][j-8]);
				}
			}
			*pGPIOD_OutputReg |= (1<<i);	// make row high back
		}
	}


    /* Loop forever */
	for(;;);
}

void softwareDelay(uint32_t timeInMillis)
{
	for(uint32_t i = 0;  i < timeInMillis * 1600 ; i++);
}

