/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void task1_handler(void);	// this is task1
void task2_handler(void);	// this is task2
void task3_handler(void);	// this is task3
void task4_handler(void);	// this is task4 of the application

void init_systick_timer(uint32_t sched_top_of_stack);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_task_stack(void);
void enable_processor_faults(void);
__attribute__((naked)) void switch_sp_to_psp(void);
uint32_t get_psp_value(void);
void save_psp_value(uint32_t current_psp_value);
void software_delay(uint8_t led_no, uint32_t count_delay);

uint32_t psp_of_task[MAX_TASK] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};

uint32_t task_handlers[MAX_TASK];

uint8_t current_task = 0; // task1 is running

/*typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASK];*/


int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	task_handlers[0] = (uint32_t)task1_handler;
	task_handlers[1] = (uint32_t)task2_handler;
	task_handlers[2] = (uint32_t)task3_handler;
	task_handlers[3] = (uint32_t)task4_handler;

	init_task_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}

void software_delay(uint8_t led_no, uint32_t count_delay)
{
	led_on(led_no);
	delay(count_delay);
	led_off(led_no);
	delay(count_delay);
}

void task1_handler(void)
{
	while(1)
	{
		software_delay(LED_GREEN,DELAY_COUNT_1S);
	}
}

void task2_handler(void)
{
	while(1)
	{
		software_delay(LED_ORANGE,DELAY_COUNT_500MS);
	}
}

void task3_handler(void)
{
	while(1)
	{
		software_delay(LED_BLUE,DELAY_COUNT_250MS);
	}
}

void task4_handler(void)
{
	while(1)
	{
		software_delay(LED_RED,DELAY_COUNT_125MS);
	}
}

void init_systick_timer(uint32_t tick_hz)
{
	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;
	uint32_t *pSRVR = (uint32_t*) SYST_RVR;
	uint32_t *pSCSR = (uint32_t*) SYST_CSR;

	// clear the value of SVR
	*pSRVR &= ~(0x00FFFFFF);

	// load the value into SVR
	*pSRVR |= count_value;

	// do some settings
	*pSCSR |= (1 << 1); // enable the systic exception request
	*pSCSR |= (1 << 2); // indicates the clock source, processor clock source

	// enable the systic
	*pSCSR |= (1 << 0); // enable the counter

}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack)
{
	//__asm volatile("MSR MSP,R0");
	__asm volatile("MSR MSP,%0": :"r"(sched_top_of_stack));
	__asm volatile("BX LR");
}


void init_task_stack(void)
{
	uint32_t *pPSP;
	for(int i = 0; i < MAX_TASK; i++)
	{
		pPSP = (uint32_t*)psp_of_task[i];

		pPSP--;	// PSR
		*pPSP = DUMMY_XPSR; // 0x01000000

		pPSP--;	// PC
		*pPSP = task_handlers[i];

		pPSP--; //LR
		*pPSP = 0xFFFFFFFD;

		for(int j = 0; j < 13; j++)
		{
			pPSP--; // for general purpose registers
			*pPSP = 0;
		}

		psp_of_task[i] = (uint32_t)pPSP;

	}
}

void HardFault_Handler(void)
{
	printf("Exception : HardFault\n");
	while(1);
}
void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}
void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}

void UsageFault_Handler(void)
{
	printf("Exception : UsageFault\n");
	while(1);
}


void enable_processor_faults(void)
{
	// 1.enable all configurable exceptions like usage fault, mem manage fault, and bus fault
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16); // mem manage
	*pSHCSR |= (1 << 17); // bus fault
	*pSHCSR |= (1 << 18); // usage fault

}

void update_next_task(void)
{
	current_task++;
	current_task %= MAX_TASK;
}

uint32_t get_psp_value(void)
{
	return psp_of_task[current_task];
}

void save_psp_value(uint32_t current_psp_value)
{
	psp_of_task[current_task] = current_psp_value;
}

__attribute__((naked)) void switch_sp_to_psp(void)
{
	// 1. initialize the PSP with TASK1 stack start address

	// get the value of psp of current task
	__asm volatile("PUSH {LR}");	// preserve LR which connects back to main()
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP,R0");	// the return value will be stored in R0 , initialize psp
	__asm volatile("POP {LR}"); 	// pops back LR value

	// 2. change SP to PSP using CONTROL register
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");

}


// this is our scheduler
__attribute__((naked)) void SysTick_Handler(void)
{
	/*save the context of current task*/

	// 1. get the current running task's PSP value
	__asm volatile("MRS R0,PSP");

	// 2. Using that PSP value store SF2 (R4 to R11)
	__asm volatile("STMDB R0!,{R4-R11}");

	__asm volatile("PUSH {LR}");

	// 3. Save the current value of PSP
	__asm volatile("BL save_psp_value");

	/*Retrieve the context of next task*/

	// 1. Decide next task to run
	__asm volatile("BL update_next_task");

	// 2. get its past PSP value
	__asm volatile("BL get_psp_value");

	// 3. Using that PSP value retrieve SF2 (R4 to R11)
	__asm volatile("LDMIA R0!,{R4-R11}");

	// 4. Update PSP and exit
	__asm volatile("MSR PSP,R0");

	__asm volatile("POP {LR}");

	__asm volatile("BX LR");

}


