/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	float number = 45.78976834578;
	double number2 = 45.78976834578;
	double charE = -1.60217662e-19;

    printf("Number = %0.9f\n",number);


    printf("Number2 = %0.14lf\n",number2);
    printf("Number2 = %0.2e\n",number2);

    printf("ChargeE = %0.28lf\n",charE);
    printf("ChargeE = %0.4le\n",charE);


	for(;;);
}
