/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
/**** Address of the Clock control register (AHB1ENR) ****/
#define	AHB1ENR 0x40023830 // base address of RCC (register control clock) register (0x40023800) + offset of AHB1ENR reg (0x30) Address of the clock control register in which GIOD D enable bit is in it

/**** Address of the GPID mode register (used to control mode) ****/
#define GPIOD_MODE 0x40020C00 // base address of GPIO D registers (0x40020C00) + offset of mode register (0x00) -> make the mode of pin 12 (bit 24 to 1 & 25 to 0) so that we can use them as general purpose output

/**** Address of the GPIOD output data register (used to write) ****/
#define GPIOD_OUTPUT 0x40020C14 // base address of GPIO D registers (0x40020C00) + offset of output register (0x14) -> make the mode of pin 12 (bit 24 to 1 & 25 to 0) so that we can use them as general purpose output

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	for(;;);
}
