/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// does not make any sense to store the string in the RAM , so use pointers instead or make the array global so that copying from flash to Stack happens during startup code not during runtime
	char msg1[] = "Hello how are you?"; // stored in the RAM so you can modify it as it's just a copy from flash to RAM
	char *pmsg2 = "fastbitlab.com"; // stored in the flash so you cannot modify it
	// so i's more convenient to use (char const *pmsg2 = "fastbitlab.com";)

	msg1[0] = 'b';
	pmsg2[0] = 'b'; // it's supposed to give error as it's trying to write on the flash

	printf("Message is : %s\n",msg1);
	printf("Message is : %s\n",pmsg2);

	printf("Address of 'msg1' variable = %p\n",&msg1);
	printf("Address of 'pmsg2' variable = %p\n",&pmsg2);

	printf("value of 'msg1' variable = %p\n",msg1);
	printf("value of 'pmsg2' variable = %p\n",pmsg2);

    /* Loop forever */
	for(;;);
}
