/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>

uint32_t g_button_press_count = 0;
void button_init(void);

uint32_t volatile *pEXTTIPendReg		= (uint32_t*) (0x40013C00 + 0x14);
uint32_t volatile *pClkCtrlReg			= (uint32_t*) (0x40023800 + 0x30);
uint32_t volatile *pClkCtrlRegApb2		= (uint32_t*) (0x40023800 + 0x44);
uint32_t volatile *pGPIOAModeReg		= (uint32_t*) (0x40020000 + 0x00);
uint32_t volatile *pEXTIMaskReg			= (uint32_t*) (0x40013C00 + 0x00);
uint32_t volatile *pEXTTIEdgeCtrlReg	= (uint32_t*) (0x40013C00 + 0x08);
uint32_t volatile *pNVICIRQEnReg		= (uint32_t*) (0xE000E100);


int main()
{
	button_init();

	while(1)
	{
		// Disable interrupt
		*pEXTIMaskReg &= ~(1 << 0);

		if(g_button_press_count){
			// some delay until button debouncing gets over
			for(uint32_t volatile i = 0; i < 50000/2 ; i++);
			g_button_press_count++;
			printf("Button is pressed : %lu\n",g_button_press_count);
			g_button_press_count = 0;
		}

		// Enable interrupt
		*pEXTIMaskReg |= (1 << 0);

	}

    return 0;
}

/*configuration of gpio pin , exti edge detection ,masking and NVIC irq enable*/
void button_init(void)
{
	/*GPIOA clock enable*/
	*pClkCtrlReg |= (1 << 0);

	/*syscfg clock enable*/
	*pClkCtrlRegApb2 |= (1 << 14);

	/*Edge detection configuration*/
	*pEXTTIEdgeCtrlReg |= (1 << 0);

	/*EXTI interrupt enable*/
	*pEXTIMaskReg |= (1 << 0);

	/*NVIC irq enable*/
	*pNVICIRQEnReg |= (1 << 6);
}

/* This is button interrupt handler*/
void EXTI0_IRQHandler(void)
{
	// Make this flag SET , if button pressed
	g_button_press_count = 1;

	// Clearing of exti interrupt pending bit
	*pEXTTIPendReg |= (1 << 0);
}
